# **LANDUSE DATASET**

# **1. 래스터(TIF) 데이터 집계: Zonal Statistics (구역 통계)**
- .tif 데이터를 L2(시/군/구) 행정구역(Shapefile) 단위로 변환합니다.
- 구역통계 방법 : 폴리곤 내에 포함되는 래스터 픽셀 값들의 평균 계산
- shapefile은 GROW-Africa database의 shapefile 이용

In [6]:
#google drive의 COSE362-term-project/dataset 폴더와 연결
from google.colab import drive

drive.mount('/content/drive')

!ls /content/drive/MyDrive/COSE362-term-project/dataset

import sys

sys.path.append('/content/drive/MyDrive/COSE362-term-project/dataset')

import os

os.chdir("/content/drive/MyDrive/COSE362-term-project/dataset")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
baseline  crop	landuse  Shapefiles

In [7]:
!ls

baseline  crop	landuse  Shapefiles

In [8]:
!pip install rasterstats

Requirement already satisfied: rasterstats in /usr/local/lib/python3.12/dist-packages (0.20.0)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from rasterstats) (2.4.0)
Requirement already satisfied: click>7.1 in /usr/local/lib/python3.12/dist-packages (from rasterstats) (8.3.0)
Requirement already satisfied: cligj>=0.4 in /usr/local/lib/python3.12/dist-packages (from rasterstats) (0.7.2)
Requirement already satisfied: fiona in /usr/local/lib/python3.12/dist-packages (from rasterstats) (1.10.1)
Requirement already satisfied: numpy>=1.9 in /usr/local/lib/python3.12/dist-packages (from rasterstats) (2.0.2)
Requirement already satisfied: rasterio>=1.0 in /usr/local/lib/python3.12/dist-packages (from rasterstats) (1.4.3)
Requirement already satisfied: simplejson in /usr/local/lib/python3.12/dist-packages (from rasterstats) (3.20.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.12/dist-packages (from rasterstats) (2.1.2)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.0->rasterstats) (25.4.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.0->rasterstats) (2025.10.5)
Requirement already satisfied: click-plugins in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.0->rasterstats) (1.1.1.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.0->rasterstats) (3.2.5)

In [13]:
from rasterstats import zonal_stats
import geopandas as gpd
import glob
import numpy as np

# 1. 지역구 지도(Shapefile)를 불러옵니다 (GROW-Africa)
regions = gpd.read_file("../final_dataset/africa_shapefile/afr_g2014_2013_1.shp")

# 2. 1km 평균 tif 파일
# africa_1km_avg_{year}
landuse_1km_raster = "landuse/africa_1km_avg_2019.tif"

# 3. 구역 통계 실행 (sum/count 대신 'mean'을 요청)
#    (이 TIF 파일 자체가 0~256 사이의 평균값이므로, 'mean'을 구하면 됨)
print("Zonal statistics 시작... ")
stats = zonal_stats(regions, landuse_1km_raster, stats="mean")

# 4. 'mean' 값만 추출
mean_values = [s['mean'] if s and s['mean'] else 0 for s in stats]

# 5. 최종 '정착률' 계산 (0.0 ~ 1.0)
#    (픽셀 값이 0~256 사이의 평균값이므로, 256으로 나누면 비율이 됨)
regions['rate_landuse'] = [val / 256 for val in mean_values]

print("모든 계산 완료!")

landuse_2019_df = regions.sort_values(by='rate_landuse',ascending=False)
landuse_2019_df
#print(sorted_df[['GID_1', 'COUNTRY','NAME_1','rate_landuse']].head())

Zonal statistics 시작...
모든 계산 완료!

,ADM1_CODE,ADM1_NAME,ADM0_CODE,ADM0_NAME,CONTINENT,REGION,geometry,rate_landuse
74,616,Littoral,29,Benin,Africa,Western Africa,"MULTIPOLYGON (((2.45327 6.37587, 2.46964 6.373...",0.949646
658,42182,Kampala,253,Uganda,Africa,Eastern Africa,"POLYGON ((32.60352 0.40659, 32.60411 0.40593, ...",0.892944
823,67154,Bangui,49,Central African Republic,Africa,Middle Africa,"POLYGON ((18.62427 4.35711, 18.62 4.35675, 18....",0.798377
760,61184,Mont Fleuri,220,Seychelles,Africa,Eastern Africa,"POLYGON ((55.45727 -4.62906, 55.46482 -4.63091...",0.781250
352,1926,Bamako,155,Mali,Africa,Western Africa,"POLYGON ((-7.93072 12.68249, -7.92764 12.68191...",0.770653
...,...,...,...,...,...,...,...,...
499,2994,Ben Arous,248,Tunisia,Africa,Northern Africa,"MULTIPOLYGON (((10.28555 36.80936, 10.28618 36...",0.000000
500,2995,Bizerte,248,Tunisia,Africa,Northern Africa,"MULTIPOLYGON (((10.18546 37.11835, 10.18528 37...",0.000000
4,344,Alger,4,Algeria,Africa,Northern Africa,"MULTIPOLYGON (((3.06823 36.77358, 3.06708 36.7...",0.000000
10,350,Blida,4,Algeria,Africa,Northern Africa,"POLYGON ((3.21015 36.67437, 3.21727 36.66692, ...",0.000000
8,348,Bejaia,4,Algeria,Africa,Northern Africa,"MULTIPOLYGON (((4.97595 36.8158, 4.97601 36.81...",0.000000

In [11]:
regions.columns

Index(['ADM1_CODE', 'ADM1_NAME', 'ADM0_CODE', 'ADM0_NAME', 'CONTINENT',
       'REGION', 'geometry', 'rate_landuse'],
      dtype='object')

In [14]:
from rasterstats import zonal_stats
import geopandas as gpd
import glob
import numpy as np

# 1. 지역구 지도(Shapefile)를 불러옵니다 (GROW-Africa)
regions = gpd.read_file("../final_dataset/africa_shapefile/afr_g2014_2013_1.shp")

# 2. 1km 평균 tif 파일
# africa_1km_avg_{year}
landuse_1km_raster = "landuse/africa_1km_avg_2015.tif"

# 3. 구역 통계 실행 (sum/count 대신 'mean'을 요청)
#    (이 TIF 파일 자체가 0~256 사이의 평균값이므로, 'mean'을 구하면 됨)
print("Zonal statistics 시작... ")
stats = zonal_stats(regions, landuse_1km_raster, stats="mean")

# 4. 'mean' 값만 추출
mean_values = [s['mean'] if s and s['mean'] else 0 for s in stats]

# 5. 최종 '정착률' 계산 (0.0 ~ 1.0)
#    (픽셀 값이 0~256 사이의 평균값이므로, 256으로 나누면 비율이 됨)
regions['rate_landuse'] = [val / 256 for val in mean_values]

print("모든 계산 완료!")

landuse_2015_df = regions.sort_values(by='rate_landuse',ascending=False)
landuse_2015_df
#print(sorted_df[['GID_1', 'COUNTRY','NAME_1','rate_landuse']].head())

Zonal statistics 시작...
모든 계산 완료!

,ADM1_CODE,ADM1_NAME,ADM0_CODE,ADM0_NAME,CONTINENT,REGION,geometry,rate_landuse
760,61184,Mont Fleuri,220,Seychelles,Africa,Eastern Africa,"POLYGON ((55.45727 -4.62906, 55.46482 -4.63091...",0.960938
74,616,Littoral,29,Benin,Africa,Western Africa,"MULTIPOLYGON (((2.45327 6.37587, 2.46964 6.373...",0.940552
757,61179,Les Mamelles,220,Seychelles,Africa,Eastern Africa,"POLYGON ((55.46993 -4.64436, 55.46995 -4.64439...",0.921875
759,61183,Mont Buxton,220,Seychelles,Africa,Eastern Africa,"POLYGON ((55.45065 -4.6199, 55.45046 -4.6201, ...",0.912109
658,42182,Kampala,253,Uganda,Africa,Eastern Africa,"POLYGON ((32.60352 0.40659, 32.60411 0.40593, ...",0.905169
...,...,...,...,...,...,...,...,...
501,2996,Beja,248,Tunisia,Africa,Northern Africa,"MULTIPOLYGON (((8.98673 37.10861, 8.98609 37.1...",0.000000
520,3015,Tunis,248,Tunisia,Africa,Northern Africa,"MULTIPOLYGON (((10.21207 36.79887, 10.21203 36...",0.000000
39,379,Skikda,4,Algeria,Africa,Northern Africa,"MULTIPOLYGON (((6.89043 36.91942, 6.89011 36.9...",0.000000
45,385,Tipaza,4,Algeria,Africa,Northern Africa,"MULTIPOLYGON (((2.05294 36.57807, 2.05311 36.5...",0.000000
47,387,Tizi Ouzou,4,Algeria,Africa,Northern Africa,"MULTIPOLYGON (((4.12107 36.89857, 4.1217 36.89...",0.000000

# **2.csv 변환하기**

In [16]:
final_2015_df = landuse_2015_df[[
    'ADM0_CODE',
    'ADM0_NAME',
    'ADM1_CODE',
    'ADM1_NAME',
    'rate_landuse'
]]

# 2. 깨끗한 CSV 파일로 저장
# landuse_{year}.csv
final_2015_df.to_csv("../final_dataset/processed_landuse_2015.csv", index=False)

print("최종 피처 테이블 저장 완료!")

최종 피처 테이블 저장 완료!

In [17]:
final_2019_df = landuse_2019_df[[
    'ADM0_CODE',
    'ADM0_NAME',
    'ADM1_CODE',
    'ADM1_NAME',
    'rate_landuse'
]]

# 2. 깨끗한 CSV 파일로 저장
# landuse_{year}.csv
final_2019_df.to_csv("../final_dataset/processed_landuse_2019.csv", index=False)

print("최종 피처 테이블 저장 완료!")

최종 피처 테이블 저장 완료!